apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dependson-reader
rules:
- apiGroups: [""]
  resources:
  - pods
  - services
  # If you use configMaps, this is required
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups: ["apps"]
  resources:
  - deployments
  - statefulsets
  - replicasets
  - daemonsets
  verbs:
  - get
  - list
  - watch

